property_id: "properties/xxx"
key_file_location: "/analytics-read-user.json"
aws_region: "us-east-2"
aws_access_key_id: ""
aws_secret_access_key: ""
rds_cluster_name: "cluster"
redis_oss_name: "prod"
eks_cluster_name: "app-prod"
cluster_context: "arn:aws:eks:us-east-2:xxxxxxx:cluster/app-prod"
kube_file_path: "~/.kube/config"
feishu_webhook_url: "https://open.feishu.cn/open-apis/bot/v2/hook/"
mysql_host: ""
mysql_port: 3306
mysql_user: ""
mysql_pwd: ""
mysql_db: "scaling_db"
hpa_name: "ingressgateway-hpa"
hpa_namespace: "istio-system"
hpa_service_name: "istio-ingressgateway"
check_time: 5